version: '3.9'

services:
  wallet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'elm-wallet'
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/elm
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: postgres:13.15-bullseye
    environment:
      POSTGRES_DB: elm
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
    volumes:
      - elm_volume:/var/lib/postgres/data

volumes:
  elm_volume:
