spring:
  application:
    name: elm-wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet-srv
    password: test
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect