spring:
  application:
    name: elm-wallet
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/elm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug
  server:
    port: 8080